version: '3'

services:
   mysql:
     image: mysql:5.6
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: P@ssw0rd
    
   processmaker:
     depends_on:
     - mysql
     image: processmaker/processmaker:latest
     ports:
       - "60000:80"
     restart: always
 
networks:
  pm-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.150.0/24
