version: "2.1"

services:
   mysql:
     image: mysql:5.6
     container_name: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: DuvxgN3uFGAy8z94gSds
     networks:
     - pm-net

   processmaker:
     depends_on:
     - mysql
     image: processmaker/processmaker:testing
     ports:
       - "80:80"
     restart: always
     networks:
      - pm-net

networks:
  pm-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.150.0/24
